issuer: Hanlon Environmental Ltd
keywords:
- hanlonplumbing.co.nz
- Environmental

fields: 
  invoice_number: 'INVOICE\s*NO.?\s*\:?\s*(\w+)'
  bc_number: '(?<!c\/\-)Body\s*Cor?porate\s*No\s*(\w+)'
  gst_number: 'GST.*?(\d{2,3}\-\d\d\d\-\d\d\d)\s'
  date: '(\d{1,2}.\d{2}.20\d\d)\s'
  due_date: '(\d{1,2}.\d{2}.20\d\d)\s'
  amount: 'Balance.*?\$?\s*([\d\,]{1,10}\.[\d]{2})'
  gst: '15%'

options:
  currency: NZD
  remove_whitespace: false
  date_formats:
    - '%d.%m.%y'
    - '%b %d, %Y'
    - '%d %b %Y'
    - '%d %b %y'
    - '%d/%m/%Y'
    - '%d/%m/%y'
    - '%d/%M/%y'
    - '%d-%b-%y'
    - '%d-%b-%Y'
    - '%d-%m-%y'

