issuer: ARMOURGUARD SECURITY
keywords:
- 'armourguard.co.nz'

fields:
  invoice_number: '[Ii][Nn][Vv][Oo][Ii][Cc][Ee]\s*[Nn]?[Uu]?[Mm]?[Bb]?[Ee]?[Rr]?[Oo]?\s*\.\s*(\d+)'
  bc_number: '(?<!C\/\-)\sB[oO]?[Dd]?[Yy]?\s*[Cc][oO]?[Rr]?[Pp]?[Oo]?[Rr]?[Aa]?[Tt]?[Ee]?\s*[Aa]?[Dd]?[Mm]?[Ii]?[ni]?[Ss]?[Tt]?[Rr]?[Aa]?[Tt]?[Ii]?[Oo]?[Nn]?[Oo]?\s*[Bb]?[Cc]?\. *(\d+)\s(?!\s*Ltd)'
  static_gst_number: '120-696-874'
  date: '[Dd][Aa][Tt][Ee].*[^\d](\d{1,2}[^\d]+\d{1,2}[^\d]+20\d\d)[^\d]'
  due_date: 'Due\s*Date.*[^\d](\d{1,2}[^\d]+\d{1,2}[^\d]+20\d\d)[^\d]'
  amount: '[aA][Mm][Oo][Uu][Nn][Tt]\s*[Dd][Uu][Ee].*\s\$?([\d\,]{1,10}\.[\d]{2})'
  gst: '15%'

options:
  currency: NZD
  remove_whitespace: false
  date_formats:
    - '%d-%b-%y'
    - '%d-%m-%y'
    - '%d.%m.%Y'
    - '%B %d'
    - '%b %d, %Y'
    - '%d %b %Y'
    - '%d %b %y'
    - '%d/%m/%Y'
    - '%d/%m/%y'
    - '%d/%M/%y'
    - '%d-%b-%Y'


